version: "3"
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfiles/server.Dockerfile
      args:
        adm_path: ${ADM_PATH}
        game_path: ${GAME_PATH}
        db_path: ${DB_PATH}
    command: "npm run server"
    working_dir: /home/node/app/backend
    networks:
      webdb:
        ipv4_address: 172.16.10.2
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - PASSWORD=${PASSWORD}
      - ADM_PATH=${ADM_PATH}
      - GAME_PATH=${GAME_PATH}
      - DB_PATH=${DB_PATH}
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./Dockerfiles/db.Dockerfile
    expose:
      - "5432"
    container_name: postgres
    networks:
      webdb:
        ipv4_address: 172.16.10.3
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  webdb:
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24
